### ISSUE TITLE
test1.html 연결

### ISSUE THREAD

**Issue by hO-chan** [hO-chan/24_OSS_13#12]
![image](https://github.com/user-attachments/assets/0bbefdda-a737-45ef-bb00-0687a726410e)

깃허브io로 만든 페이지에서 test1.html로 안가지네요

**Comment by Jbchan01** [comment]
http 오류, https

**Comment by 0lemoncandy0** [comment]
https  로 엔드 포인트 바꾸고 핑퐁
io에서 http는 막기 떄문
