### ISSUE TITLE
병원 찾기 오류

### ISSUE THREAD

**Issue by hO-chan** [hO-chan/24_OSS_13#13]
![병원찾기오류](https://github.com/user-attachments/assets/258893d9-3500-45fe-966c-090d002315e6)

Failed to Fetch 뜨는 데 어떻게 해야하나요?

**Comment by 0lemoncandy0** [comment]
GitHub Pages처럼 https 환경에서는 http 요청이 차단되기 때문에 프록시 서버를 구축하거나 로컬 개발 환경을 사용해야함. https 버전 엔드포인트가 없으면 프록시 서버가 가장 확실한 해결 방법하고 여기선, https로 변경만 하면됨

**Comment by hO-chan** [comment]
확인했습니다. 잘되네요
